["protostar.config"]
protostar_version = "0.5.0"

["protostar.project"]
libs_path = "lib"

["protostar.contracts"]
Will = [
    "src/will.cairo",
]

["profile.devnet.protostar.shared_command_configs"]
gateway_url="http://localhost:5050"
chain_id="1536727068981429685321"