["protostar.config"]
protostar_version = "0.5.0"

["protostar.project"]
libs_path = "lib"

["protostar.contracts"]
will = [
    "src/will.cairo",
]
will_factory = [
    "src/will_factory.cairo"
]
argent_account_extended = [
    "src/account/argent_account_extended.cairo"
]

["protostar.shared_command_configs"]
cairo-path = ["./lib/cairo_contracts/src", "./lib/argent_contracts_starknet/contracts"]

["profile.devnet.protostar.shared_command_configs"]
gateway-url = "http://localhost:5050"
chain-id = 1536727068981429685321

