["protostar.config"]
protostar_version = "0.5.0"

["protostar.project"]
libs_path = "lib"

["protostar.contracts"]
will = [
    "src/will.cairo",
]

["protostar.shared_command_configs"]
cairo-path = ["./lib/cairo_contracts/src", "./lib/argent_contracts_starknet/contracts"]
